language: python

python:
  - "2.7"

env:
  global:
    secure: omFMs9SEGjhu4q4oVpF08LaPhh8q9ytaerRVyo1TrAdWsxNGfqjgUFHEFUN56AecmP31atwcA0EdBc+qmbxH/fHQIlQAU38vlfn6b9VuAW8h2pjhimxYuz6eAob47nLyPxMDqKeJSpNhmj1CN+fxWL2SxZWIsWHqq4jGlkn+Ft0=

before_install:
  - sudo apt-get install -qq gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pytest flake8 sphinx lxml sqlalchemy mock netcdf4
  - pip install --use-mirrors suds
  - pip install --use-mirrors sphinx-bootstrap-theme
  - pip install obspy
  - pip install coveralls

install:
  - pip install --no-deps -v -e .

script:
  - coverage run --source=instaseis -m instaseis.tests
  - cd $TRAVIS_BUILD_DIR/doc; make html

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls debug
  - bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh
